server:
  port: 8082 # 由于8081端口被占用，临时修改为8082

app:
  upload-dir: D:/px/backend/uploads
  
spring:
  application:
    name: px_work-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platrom?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "root"
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台 SQL 打印
  global-config:
    db-config:
      id-type: auto # 配置主键自增

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  is-read-header: true
  is-read-cookie: true
  token-style: uuid

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

ai:
  dify:
    base-url: "http://192.168.1.51/v1"
    api-key: "app-xxxxxxxxxxxxxxxxxxxxxxxx" # 请保持这个占位符，稍后我会自己换成真实的秘钥
